### ISSUE TITLE
Exporting png with scaling just extends the png

### ISSUE THREAD

**Issue by Antlux** [MewPurPur/GodSVG#569] opened 2024-03-06 01:19 UTC
I am using the latest released version of GodSVG for windows as of posting this issue.

I am encountering issues with exporting scaled vector drawings to png : Scaling just extends the png, it does not scale the actual drawing.

I do not think this is intended because this,
![image](https://github.com/MewPurPur/GodSVG/assets/118110096/d492dea0-b477-4ec9-a7b6-9c6713d8fc55)

outputs this,
![rocket](https://github.com/MewPurPur/GodSVG/assets/118110096/245361bf-113f-4195-b5f5-a19bd72a9937)

**Comment by MewPurPur** [comment] 2024-03-06 01:20
This is alpha 2, not the current master, right?

**Comment by Antlux** [comment] 2024-03-06 01:21
Yes, I forgot to say

**Comment by MewPurPur** [comment] 2024-03-06 01:22
Can't reproduce this on the latest branch, it must have been fixed over the last two months. So this will be fixed in the next alpha soon.

**Comment by Antlux** [comment] 2024-03-06 01:23
Right, thank you

**Comment by Antlux** [comment] 2024-03-06 01:29
By the way, to try and export it using the current main branch build I would just have to clone the repo and do it with that?

**Comment by Antlux** [comment] 2024-03-06 01:32
If so, using this build produces the same error on my computer.

**Comment by MewPurPur** [comment] 2024-03-06 07:19
Very odd, I can't reproduce. Could you post the graphic?

**Comment by MewPurPur** [comment] 2024-03-06 08:57
Nevermind, I reproduce it.

**Comment by Antlux** [comment] 2024-03-06 09:05
Ok, i will try that, thank you

**Closed** 2024-03-07 21:47 UTC
Labels: bug
