### ISSUE TITLE
Add option for hot-reloading translations

### ISSUE THREAD

**Issue by Vovkiv** [MewPurPur/GodSVG#608] opened 2024-03-20 18:27 UTC
There more there strings in program, then harder it become translating and debugging it.
It would be nice to have option to reload translations without need to restart GodSVG.

Currently, translation workflow looks like this:

1. Make some changes in po file.
2. Open GodSVG, switch to desired language.
3. Check if everything right.
4. If not, translate/fix this in po file.
5. Close GodSVG, switch back to Godot so it will re-import translations.
6. Start GodSVG again.
7. Goto 1.

This is kind of slow and require to much actions.
There should be possibility to restart translation on demand, preferably by some ui button and/or keyboard shortcut, for example, F5 (in this case, this option should be available only in dev build, not in public one).

I'm not sure if this currently possible in Godot, but maybe this https://docs.godotengine.org/en/stable/classes/class_translation.html will be good starting point.
Main idea here is to get list of already added to project settings translations (so we can have path to files) and then force reload and reapply them.

**Comment by Kiisu-Master** [comment] 2024-03-20 19:15
Maybe my memory wrong but for me it was more like
1. change translation
2. restart GodSVG in editor
3. realise something translated wrong, goto 1

**Comment by Vovkiv** [comment] 2024-03-20 19:29
> Maybe my memory wrong but for me it was more like
> 
>     1. change translation
> 
>     2. restart GodSVG in editor
> 
>     3. realise something translated wrong, goto 1
> 
> 
> How did you make that 7 steps!

I think it more about how you would count steps, but my main problem is that I need to do more actions and switch between 3-4 programs to test something in translations (and remember that you need to this steps everytime), including time required when GodSVG will restart which takes 1.5 seconds everytime, which will add up.
In my own case also ads up fact, that I work on 2 translations, so I need to spend twice as much time to finish, which is really adds up! 

> It never bothered me and it honestly doesn't seem worth it taking the development time and adding a bit more complexity to the program, to optimize a little kink in the development workflow that takes like 10sec very occasionally.

It's less about saving _time_, but more about saving _mental state_, will to work on translation. The more I switch between various programs to achieve something, the more I get tired and annoyed, and as result I might start make more typos, more lazy translations, etc. In worst case scenario might get enough annoyed to stop working altogether! (which is probably more like edge case, but still, something that happened with me several times).

And while implementing this hotswap feature might make less sense to implement per program, it might be more interesting to implement it on Godot level. Some kind of global assets reloader.
I don't think there opened PRs about this or built in functionality?

**Comment by MewPurPur** [comment] 2024-03-29 00:05
Closing this proposal as not planned and ruled out. This is not a reflection of the validity of your request, but rather a result of balancing priorities. If someone can make a PR solving this, it might still be accepted, but the issue will not be worked on by me.

My reasoning:

- This seems impossible to solve on our end.
- I don't even think many translators would benefit from this, as you don't _need_ to re-open GodSVG many times over while translating.
- The app is by design not monolithic, so it should always remain very manageable to translate it. The little inconveniences won't add up enough to justify spending development time for the limited benefits this little hack would bring.

**Closed by MewPurPur** 2024-03-29 00:05 UTC
Labels: proposal
